### ISSUE TITLE
Strange behaviour of inreal-outreal

### ISSUE THREAD

**Issue by fred5678** [JvanKatwijk/algol-60-compiler#6]
As you can see in test.inp the program test.alg reads the first number 1.0 and shows it as -19.0 (1 - 20). I started it with ./test < test.inp.
[test.alg.txt](https://github.com/JvanKatwijk/algol-60-compiler/files/2944837/test.alg.txt)
[test.inp.txt](https://github.com/JvanKatwijk/algol-60-compiler/files/2944838/test.inp.txt)

**Comment by JvanKatwijk** [comment]
Right now I am not at home, will be back some time next week

**Comment by JvanKatwijk** [comment]
[jan@lenovo Downloads]$ ./test-inout < test.inp.txt 
1.000000000 -7.348469228 0.0 0.0 0.0 -7.348469228 42.09259259 5.763128389 0.0 0.0 0.0 5.763128389 0.9725900074 -0.3706217812 0.0 0.0 0.0 -0.3706217812 0.3830239708 -0.2392858992 0.0 0.0 0.0 -0.2392858992 0.5517934291 [jan@lenovo Downloads]$

The inputfile contained a control character in front of the 1.00

**Comment by fred5678** [comment]
Now I know how it happened. I redirected the output in a file and copy-pasted it in a new one.
Thanks a lot.
